### ISSUE TITLE
bug knex

### ISSUE THREAD

**Issue by pierluc-codes** [simonstre/tablebot#2]
je crois qu'il y a un bug dans knex.

le schema est defini par t.timestamp( 'date' ).defaultTo( 'now()' ).notNullable();

cependant, dans mon postgres date() est interpret de la date du creaiton du schema je crois.

CREATE TABLE games
(
  id serial NOT NULL,
  players integer NOT NULL DEFAULT 0,
  date timestamp with time zone NOT NULL DEFAULT '2016-05-11 22:29:29.951198-04'::timestamp with time zone,
  messageid text NOT NULL,
  channelid text NOT NULL,
  CONSTRAINT games_pkey PRIMARY KEY (id)
)

**Comment by pierluc-codes** [comment]
https://github.com/tgriesser/knex/issues/271

**Comment by simonstre** [comment]
Oui merci, corrigé par https://github.com/simonstre/tablebot/commit/71439c278726be91869d9503a30c5aee35484e25.
